spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
eureka.client.service-url.defaultZone=http://localhost:2222/eureka
# Zipkin endpoint
spring.zipkin.base-url=http://127.0.0.1:9411

# Sample 100% of requests (recommended for dev / learning)
spring.sleuth.sampler.probability=1.0

